= AsciiCSAND: Asciidoctor processor for CSA Normal Documents (CSAND)

image:https://img.shields.io/gem/v/metanorma-csand.svg["Gem Version", link="https://rubygems.org/gems/metanorma-csand"]
image:https://img.shields.io/travis/riboseinc/metanorma-csand/master.svg["Build Status", link="https://travis-ci.com/riboseinc/metanorma-csand"]
image:https://codeclimate.com/github/riboseinc/metanorma-csand/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/metanorma-csand"]

WARNING: This gem is still under development.

_Formerly known as_ `asciidoctor-csand`.

== Functionality

This gem processes http://asciidoctor.org/[Asciidoctor] documents following
a template for generating CSAND documents.

The gem currently inherits from the https://github.com/riboseinc/metanorma-standoc
gem, and aligns closely to it. Refer to the ISO gem documentation
for guidance, including https://github.com/riboseinc/metanorma-iso/wiki/Guidance-for-authoring

The following outputs are generated.

* (Optional) An HTML preview generated directly from the Asciidoctor document,
using native Asciidoctor formatting.
** http://asciimath.org[AsciiMathML] is to be used for mathematical formatting.
The gem uses the https://github.com/asciidoctor/asciimath[Ruby AsciiMath parser],
which is syntactically stricter than the common MathJax processor;
if you do not get expected results, try bracketing terms your in AsciiMathML
expressions.
* an XML representation of the document, intended as a document model for CSAND
International Standards.
* The XML representation is processed in turn to generate the following outputs
as end deliverable CSAND standard drafts.
** HTML output.

This AsciiDoc syntax for writing CSAND standards is hereby named "AsciiCSAND".

== Usage

The preferred way to invoke this gem is via the `metanorma` script:

[source,console]
----
$ metanorma --type csand a.adoc                   # output just HTML
$ metanorma --type csand a.adoc --extensions html # output just HTML
$ metanorma --type csand a.adoc --extensions xml  # output CSAND XML
----

The gem translates the document into CSAND XML format, and then
validates its output against the CSAND XML document model; errors are
reported to console against the XML, and are intended for users to
check that they have provided all necessary components of the
document.

The gem then converts the XML to HTML, and
outputs that files with the appropriate `.html` suffix.

The gem can also be invoked directly within asciidoctor, though this is deprecated:

[source,console]
----
$ asciidoctor -b csand -r 'asciidoctor-csand' a.adoc  
----

=== Installation

If you are using a Mac, the https://github.com/riboseinc/metanorma-macos-setup
repository has instructions on setting up your machine to run Metanorma
scripts such as this one. You need only run the following in a Terminal console:

[source,console]
----
$ bash <(curl -s https://raw.githubusercontent.com/riboseinc/metanorma-macos-setup/master/metanorma-setup)
$ gem install metanorma-csand

----

== Approach
=== Document model

The Ribose Standard Document model is an instance of the
https://github.com/riboseinc/isodoc-models[StandardDocument model].

The CSAND format ("CSAND XML") intends to introduce rigor into the CSAND
standards authoring process, and is prescribed in a separate document.

CSAND XML is still under development, but it already contains all the markup
needed to render a CSAND document into HTML.

WARNING: The current RNG model of CSAND XML is out of sync with the UML.

=== Asciidoctor

Asciidoctor has been selected as the authoring tool to generate the document
model representation of CSAND standards. It is a document formatting tool like
Markdown and DocBook, which combines the relative ease of use of the former
(using relatively lightweight markup), and the rigor and expressively of the
latter (it has a well-defined syntax, and was in fact initially developed as a
DocBook document authoring tool). Asciidoctor has built-in capability to output
Text, DocBook and HTML; so it can be used to preview the file as it is being
authored.

Generating documents via a document model substantially automated formatting
associated with the document, including automating numbering of headings, figures,
tables etc, and automatically generating references and citations.

== Document Attributes

=== Common attributes

The gem relies on Asciidoctor document attributes to provide necessary
metadata about the document. The https://github.com/riboseinc/metanorma-standoc[metanorma-standoc]
gem documents the Asciidoctor document attributes common to all metanorma gems. These include:

`:edition:`:: The document edition

`:revdate:`:: The date the document was last updated

`:copyright-year:`:: The year which will be claimed as when the copyright for
the document was issued

`:title:`:: The main component of the English title of the document
(mandatory). (The first line of the AsciiDoc document, which contains the title
introduced with `=`, is ignored)

`:doctype:`:: The document type (see CSAND deliverables: The different types of
CSAND publications) (mandatory). The permitted types are:
+
--
guidance, proposal, standard, report, whitepaper, charter, policy, glossary, case-study
--

`:status:``:: The document status. The permitted types are: `proposal`,
`working-draft`, `committee-draft`, `draft-standard`, `final-draft`,
`published`, `withdrawn`.

`:committee:`:: The name of the relevant CSAND technical committee
(mandatory)

`:language:` :: The language of the document (only `en` for now)  (mandatory)


The attribute `:draft:`, if present, includes review notes in the XML output;
these are otherwise suppressed.

== Asciidoctor features specific to CSAND

The https://github.com/riboseinc/metanorma-standoc[metanorma-standoc]
gem documents the customisations of Asciidoctor markup common to all metanorma gems. 
The following markup is specific to this gem:

* `+[keyword]#...#+`: encodes keywords, such as "MUST", "MUST NOT". (Encoded as
`<span class="keyword">...</span>`.

== Data Models

The CSAND Standard Document format is an instance of the
https://github.com/riboseinc/isodoc-models[StandardDocument model]. Details of
this general model can be found on its page. Details of the CSAND modifications
to this general model can be found on the https://github.com/riboseinc/csand[CSAND model]
repository.

== Examples

* link:spec/examples/rfc6350.adoc[] is an AsciiCSAND version of https://tools.ietf.org/html/rfc6350[RFC 6350].
* link:spec/examples/rfc6350.html[] is an HTML file generated from the AsciiCSAND.
* link:spec/examples/rfc6350.doc[] is a Word document generated from the AsciiCSAND.
